apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: azure-ad
  title: Microsoft Entra ID
spec:
  type: service-offering
  profile:
    cloudProvider: Azure
    serviceCategory: Security
    serviceDescription: >-
      Cloud-based identity and access management for employees, partners, and customers at
      enterprise scale.
    serviceExternalDoc: https://learn.microsoft.com/en-us/azure/
    serviceInternalDoc: https://cloud-docs.cbp.dhs.gov/
    provisioningModel: Tier 2
    cloudAto:
      - CMAA
    serviceOwner: Wanda Maximoff
    fedRampStatus: FedRAMP Certified
    trmStatus: Permitted
    trmLink: https://cloud-docs.cbp.dhs.gov/governance/trm.html#azure-ad
    fundingApproach: ECSD pay
    approvalWorkflow: Manager Approval
    provisioningSLA: 2 business days
    serviceUseCases:
      - Single sign-on federation
      - MFA enforcement
      - Conditional access policies
      - B2B external identity management
