apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: azure-blob
  title: Azure Blob Storage
spec:
  type: service-offering
  lifecycle: production
  profile:
    cloudProvider: Azure
    serviceCategory: Storage
    serviceDescription: Massively scalable object storage for unstructured data including documents, media files, and backups.
    serviceExternalDoc: https://learn.microsoft.com/en-us/azure/
    serviceInternalDoc: https://cloud-docs.cbp.dhs.gov/
    provisioningModel: Tier 1
    cloudAto:
      - CMAA
    serviceOwner: Wanda Maximoff
    fedRampStatus: FedRAMP Certified
    trmStatus: Permitted
    trmLink: https://cloud-docs.cbp.dhs.gov/governance/trm.html#azure-blob
    fundingApproach: ECSD pay
    approvalWorkflow: Auto-Approved
    provisioningSLA: Same day
    serviceUseCases:
      - Backup and disaster recovery
      - Data lake and analytics
      - Static content delivery
      - Log and telemetry archiving
