#!/usr/bin/env node
// Compiles src/styles/servicelog-plugin.css (Tailwind entry, see STORY 2.3
// checkpoint B1) and wraps the result as a plain TS string module under
// src/styles/generated/ (gitignored, regenerated by prebuild/prestart --
// see .gitignore). Not a plain .css file, and not written under dist/:
// `backstage-cli package build`'s bundler for the `frontend-plugin` role
// only resolves modules inside this package's own src/ tree, and has no
// CSS loader in any case (unlike the app-role webpack build) -- a string
// export living in src/ is just an ordinary module any bundler follows.
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import postcss from 'postcss';
import prefixSelector from 'postcss-prefix-selector';
// Deep import straight to @servicelog/core's compiled leaf module (which has
// no further imports of its own) rather than its public `main` entrypoint:
// this script runs under plain `node`, and that package's dist/index.js
// barrel re-exports its sibling modules without file extensions (valid
// under the bundlers every real consumer uses -- Vite/webpack/Rollup -- but
// not resolvable by Node's own stricter ESM loader), confirmed empirically
// while wiring this up. Reaching in like this keeps the class-name literal
// defined in exactly one place (../../../src/app/styles/scopeClassName.ts)
// instead of hardcoding a second copy here to drift out of sync with it.
import { SERVICELOG_SCOPE_CLASS_NAME } from '../../../src/app/dist/styles/scopeClassName.js';

const SERVICELOG_SCOPE_SELECTOR = `.${SERVICELOG_SCOPE_CLASS_NAME}`;

const root = path.resolve(import.meta.dirname, '..');
const cssOut = path.join(root, 'dist/styles/servicelog.css');
mkdirSync(path.dirname(cssOut), { recursive: true });

execFileSync(
  process.platform === 'win32' ? 'npx.cmd' : 'npx',
  ['tailwindcss', '-i', 'src/styles/servicelog-plugin.css', '-o', cssOut, '--minify'],
  { cwd: root, stdio: 'inherit' },
);

// Tailwind compiles servicelog-plugin.css's hand-written `.servicelog-scope`
// rules exactly as written, but it has no idea those rules exist for
// containment purposes -- everything IT generates (every utility selector
// from utilities.css, and the `:root, :host` theme-token block from
// theme.css) comes out unscoped, plus @servicelog/core/styles/tokens.css's
// own unscoped `:root`/`.dark` blocks (that file is intentionally
// host-neutral input, see its header). Left alone, all of that is injected
// as a global <style> tag (see ../src/styles/useInjectPluginStyles.ts) that
// any other Backstage page's `.flex`/`.dark`/etc. would also match. This
// pass rewrites every selector in the compiled output to require
// `.servicelog-scope` -- either as an ancestor (the ordinary case) or, for
// `:root`/`:host`/`.dark`, AS the scope element itself, since custom
// properties only cascade to descendants when declared on an ancestor (or
// self), never via a "descendant of :root" selector, which cannot match
// anything. Selectors already written against `.servicelog-scope` by hand
// (the preflight-replacement reset above) are left untouched instead of
// double-prefixed. `@property`/`@keyframes` at-rules are untouched by this
// (walkRules does not visit them) and stay global -- inherent to the CSS
// platform, not something a selector prefix can scope; see
// docs/backstage-compatibility.md section 4b for why that's an accepted,
// low-risk exception rather than a gap in this pass.
const scoped = postcss([
  prefixSelector({
    prefix: SERVICELOG_SCOPE_SELECTOR,
    transform(prefix, selector, prefixed) {
      if (selector === ':root' || selector === ':host') return prefix;
      if (selector === '.dark') return `${prefix}.dark`;
      if (selector.startsWith(prefix)) return selector;
      return prefixed;
    },
  }),
]).process(readFileSync(cssOut, 'utf8'), { from: cssOut, to: cssOut }).css;
writeFileSync(cssOut, scoped);

const css = readFileSync(cssOut, 'utf8');
const tsOut = path.join(root, 'src/styles/generated/servicelog-css.ts');
mkdirSync(path.dirname(tsOut), { recursive: true });
writeFileSync(
  tsOut,
  `// Generated by scripts/build-css.mjs from ../servicelog-plugin.css -- do not edit directly.\nexport const SERVICELOG_PLUGIN_CSS = ${JSON.stringify(css)};\n`,
);
