#!/usr/bin/env node
// Compiles src/styles/servicelog-plugin.css (Tailwind entry, see STORY 2.3
// checkpoint B1) and wraps the result as a plain TS string module under
// src/styles/generated/ (gitignored, regenerated by prebuild/prestart --
// see .gitignore). Not a plain .css file, and not written under dist/:
// `backstage-cli package build`'s bundler for the `frontend-plugin` role
// only resolves modules inside this package's own src/ tree, and has no
// CSS loader in any case (unlike the app-role webpack build) -- a string
// export living in src/ is just an ordinary module any bundler follows.
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const cssOut = path.join(root, 'dist/styles/servicelog.css');
mkdirSync(path.dirname(cssOut), { recursive: true });

execFileSync(
  process.platform === 'win32' ? 'npx.cmd' : 'npx',
  ['tailwindcss', '-i', 'src/styles/servicelog-plugin.css', '-o', cssOut, '--minify'],
  { cwd: root, stdio: 'inherit' },
);

const css = readFileSync(cssOut, 'utf8');
const tsOut = path.join(root, 'src/styles/generated/servicelog-css.ts');
mkdirSync(path.dirname(tsOut), { recursive: true });
writeFileSync(
  tsOut,
  `// Generated by scripts/build-css.mjs from ../servicelog-plugin.css -- do not edit directly.\nexport const SERVICELOG_PLUGIN_CSS = ${JSON.stringify(css)};\n`,
);
