import React, { useEffect, useRef, useState } from 'react';
import { Check, ChevronDown, Search, X } from 'lucide-react';
import { PROVIDERS, CATEGORIES, TrmStatus } from '../data/services';
import { TRM_STYLES } from './ServiceCard';
interface FilterBarProps { search: string; onSearchChange: (value: string) => void; selectedProviders: string[]; onProvidersChange: (providers: string[]) => void; selectedCategories: string[]; onCategoriesChange: (value: string[]) => void; selectedTrmStatuses: TrmStatus[]; onTrmStatusesChange: (value: TrmStatus[]) => void; totalCount: number; filteredCount: number; onClearAll: () => void; }
const TRM_STATUSES: TrmStatus[] = ['Permitted', 'Restricted', 'Divest', 'Prohibited'];
const PROVIDER_OPTIONS = PROVIDERS.filter((provider) => provider !== 'All') as string[];
const CATEGORY_OPTIONS = CATEGORIES.filter((category) => category !== 'All') as string[];
export function FilterBar({ search, onSearchChange, selectedProviders, onProvidersChange, selectedCategories, onCategoriesChange, selectedTrmStatuses, onTrmStatusesChange, totalCount, filteredCount, onClearAll }: FilterBarProps) {
  const [categoriesOpen, setCategoriesOpen] = useState(false);
  const categoriesRef = useRef<HTMLDivElement>(null);
  const categoriesTriggerRef = useRef<HTMLButtonElement>(null);
  const active = search.length > 0 || selectedProviders.length > 0 || selectedCategories.length > 0 || selectedTrmStatuses.length > 0;
  const [announcedCount, setAnnouncedCount] = useState(filteredCount);
  useEffect(() => {
    const timer = setTimeout(() => setAnnouncedCount(filteredCount), 500);
    return () => clearTimeout(timer);
  }, [filteredCount]);
  useEffect(() => {
    if (!categoriesOpen) return;
    const dismissOnOutsidePointerDown = (event: PointerEvent) => {
      const categories = categoriesRef.current;
      if (categories && !event.composedPath().includes(categories)) setCategoriesOpen(false);
    };
    const dismissOnEscape = (event: KeyboardEvent) => { if (event.key === 'Escape') { setCategoriesOpen(false); categoriesTriggerRef.current?.focus(); } };
    document.addEventListener('pointerdown', dismissOnOutsidePointerDown, true);
    document.addEventListener('keydown', dismissOnEscape);
    return () => { document.removeEventListener('pointerdown', dismissOnOutsidePointerDown, true); document.removeEventListener('keydown', dismissOnEscape); };
  }, [categoriesOpen]);
  const toggleProvider = (provider: string) => { const next = selectedProviders.includes(provider) ? selectedProviders.filter((item) => item !== provider) : [...selectedProviders, provider]; onProvidersChange(next.length === PROVIDER_OPTIONS.length ? [] : next); };
  const toggleCategory = (category: string) => { const next = selectedCategories.includes(category) ? selectedCategories.filter((item) => item !== category) : [...selectedCategories, category]; onCategoriesChange(next.length === CATEGORY_OPTIONS.length ? [] : next); };
  const toggleTrm = (status: TrmStatus) => { const next = selectedTrmStatuses.includes(status) ? selectedTrmStatuses.filter((item) => item !== status) : [...selectedTrmStatuses, status]; onTrmStatusesChange(next.length === TRM_STATUSES.length ? [] : next); };
  return <section className="mb-6" aria-label="Filter service offerings">
    <div className="flex flex-col gap-2 lg:flex-row lg:items-center"><label className="relative min-w-0 flex-1"><Search aria-hidden="true" className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-500" /><span className="sr-only">Search services</span><input value={search} onChange={(event) => onSearchChange(event.target.value)} placeholder="Search service offerings..." className="h-[38px] w-full rounded-lg border border-[#7c88a0] bg-white pl-11 pr-3 text-[14px] text-slate-800 outline-none placeholder:text-slate-500 focus:border-[#1565C0] focus:ring-1 focus:ring-[#1565C0]" /></label><div className="flex flex-wrap gap-2">{PROVIDERS.map((provider) => { const active = provider === 'All' ? selectedProviders.length === 0 : selectedProviders.includes(provider); return <button key={provider} type="button" onClick={() => provider === 'All' ? onProvidersChange([]) : toggleProvider(provider)} aria-pressed={active} className={`h-[34px] rounded-full border px-3 text-[13px] font-medium focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#1565C0] ${active ? 'border-[#123a80] bg-[#123a80] text-white' : 'border-[#7c88a0] bg-transparent text-[#294260] hover:bg-white'}`}>{provider === 'All' ? 'All providers' : provider}</button>; })}</div></div>
    <div className="mt-2.5 flex flex-col gap-2 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap items-center gap-2"><div ref={categoriesRef} className="relative"><button ref={categoriesTriggerRef} type="button" onClick={() => setCategoriesOpen((open) => !open)} aria-expanded={categoriesOpen} aria-controls="categories-panel" className="inline-flex h-[30px] items-center gap-1.5 rounded-md border border-[#7c88a0] bg-white px-2.5 text-[13px] font-medium text-[#1A1A2E] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#1565C0]">Categories<ChevronDown aria-hidden="true" className="size-3.5" /></button>{categoriesOpen && <div id="categories-panel" className="absolute left-0 top-9 z-20 max-h-80 w-72 overflow-y-auto rounded-md border border-slate-200 bg-white p-1.5 shadow-lg">{CATEGORY_OPTIONS.map((category) => { const checked = selectedCategories.includes(category); return <label key={category} className="flex w-full cursor-pointer items-center gap-2 rounded px-2 py-1.5 text-left text-[14px] text-slate-700 hover:bg-slate-50"><input type="checkbox" checked={checked} onChange={() => toggleCategory(category)} className="peer sr-only" /><span aria-hidden="true" className={`flex size-4 shrink-0 items-center justify-center rounded border peer-focus-visible:outline peer-focus-visible:outline-2 peer-focus-visible:outline-offset-2 peer-focus-visible:outline-[#1565C0] ${checked ? 'border-[#1565C0] bg-[#1565C0] text-white' : 'border-slate-300'}`}>{checked && <Check className="size-3" />}</span>{category}</label>; })}</div>}</div>{selectedCategories.map((category) => <span key={category} className="inline-flex items-center gap-0 rounded-full bg-[#eef3f9] pl-2 py-1 text-[12px] font-medium text-slate-700">{category}<button type="button" onClick={() => toggleCategory(category)} aria-label={`Remove ${category} filter`} className="-my-1 ml-0.5 inline-flex size-7 items-center justify-center rounded-full hover:bg-slate-200 focus-visible:outline-2 focus-visible:outline-[#1565C0]"><X aria-hidden="true" className="size-3" /></button></span>)}</div><div className="flex flex-wrap items-center gap-2"><span className="metadata-label">TRM Status:</span>{TRM_STATUSES.map((status) => { const style = TRM_STYLES[status]; const active = selectedTrmStatuses.includes(status); return <button type="button" key={status} onClick={() => toggleTrm(status)} aria-pressed={active} className={`inline-flex h-[30px] items-center gap-1.5 rounded-full border px-2.5 text-[13px] font-medium focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#1565C0] ${active ? `border-current bg-white ${style.className}` : 'border-[#7c88a0] bg-transparent text-[#294260] hover:bg-white'}`}><span aria-hidden="true" className={`size-1.5 rounded-full ${style.dot}`} />{status}</button>; })}</div></div>
    <div className="mt-2 flex items-center gap-3 text-[13px]"><p className="text-[#5a6373]">Showing {filteredCount} of {totalCount} service offerings</p><span role="status" aria-live="polite" className="sr-only">{announcedCount === 0 ? 'No service offerings match your search and filters.' : `Showing ${announcedCount} of ${totalCount} service offerings`}</span>{active && <button type="button" onClick={onClearAll} className="font-medium text-[#1565C0] hover:underline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#1565C0]">Clear all</button>}</div>
  </section>;
}
