apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: amazon-ec2
  title: Amazon EC2
spec:
  type: service-offering
  lifecycle: production
  profile:
    cloudProvider: AWS
    serviceCategory: Compute
    serviceDescription: Amazon EC2 forms a central part of the AWS cloud-computing platform, Amazon Web Services (AWS), by allowing users to rent virtual computers on which to run their own computer applications. EC2 encourages scalable deployment of applications by providing a web service through which a user can boot an Amazon Machine Image (AMI) to configure a virtual machine, which Amazon calls an "instance", containing any software desired. A user can create, launch, and terminate server-instances as needed, paying by the hour for active servers – hence the term "elastic". EC2 provides users with control over the geographical location of instances that allows for latency optimization and high levels of redundancy.
    serviceExternalDoc: https://docs.aws.amazon.com/ec2/
    serviceInternalDoc: ./platforms/iaas/ec2
    provisioningModel: Tier 1
    cloudAto:
      - CACE
    serviceOwner: Natasha Romanoff
    fedRampStatus: FedRAMP Certified
    trmStatus: Permitted
    trmLink: https://cloud-docs.cbp.dhs.gov/governance/trm.html#amazon-ec2
    fundingApproach: ECSD pay
    approvalWorkflow: Auto-Approved
    provisioningSLA: Same day
    serviceUseCases:
      - Web application hosting
      - Batch processing workloads
      - Development and test environments
      - High-performance computing
    serviceOnboardingRequirements:
      - cost-center
      - project
      - environment
      - quantity
      - operating-system (linux or windows)
      - instance-type
      - storage-size
      - tier-structure (for linux)
      - subnet-id
      - security-group-ids
