apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: amazon-dynamodb
  title: Amazon DynamoDB
spec:
  type: service-offering
  profile:
    cloudProvider: AWS
    serviceCategory: Database
    serviceDescription: >-
      Amazon DynamoDB is a fully managed proprietary NoSQL database service that is offered by
      Amazon.com as part of the Amazon Web Services portfolio. DynamoDB exposes a similar data model
      and derives its name from Dynamo, but has a different underlying implementation. Dynamo had a
      multi-master design requiring the client to resolve version conflicts, and DynamoDB uses
      synchronous replication across multiple datacenters for high durability and availability.
    serviceExternalDoc: https://docs.aws.amazon.com/dynamodb/
    serviceInternalDoc: ./platforms/development/amazon/dynamodb
    provisioningModel: Tier 1
    cloudAto:
      - CACE
    serviceOwner: Natasha Romanoff
    fedRampStatus: FedRAMP Certified
    trmStatus: Permitted
    trmLink: https://cloud-docs.cbp.dhs.gov/governance/trm.html#amazon-dynamodb
    fundingApproach: ECSD pay
    approvalWorkflow: Auto-Approved
    provisioningSLA: Same day
    serviceUseCases:
      - Session state management
      - Real-time leaderboards
      - IoT device telemetry
      - High-throughput key-value lookups
    serviceOnboardingRequirements:
      - cost_center
      - project
      - environment
      - table_name (Optional)
      - read_capacity
      - write_capacity
      - hash_key
      - range_key (Optional)
