apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: amazon-documentdb
  title: Amazon DocumentDB
spec:
  type: service-offering
  lifecycle: production
  profile:
    cloudProvider: AWS
    serviceCategory: Database
    serviceDescription: Amazon DocumentDB (with MongoDB compatibility) is a database service that is purpose-built for JSON data management at scale, fully managed and integrated with AWS, and enterprise-ready with high durability. Amazon DocumentDB is designed to give you the scalability and durability you need when operating mission-critical MongoDB workloads. Storage scales automatically up to 64TiB without any impact to your application. It supports millions of requests per second with up to 15 low latency read replicas in minutes, without any application downtime, regardless of the size of your data.
    serviceExternalDoc: https://docs.aws.amazon.com/documentdb/
    serviceInternalDoc: ./platforms/development/amazon/docudb
    provisioningModel: Tier 2
    cloudAto:
      - CACE
    serviceOwner: Natasha Romanoff
    fedRampStatus: FedRAMP Certified
    trmStatus: Permitted
    trmLink: https://cloud-docs.cbp.dhs.gov/governance/trm.html#amazon-documentdb
    fundingApproach: ECSD pay
    approvalWorkflow: Manager Approval
    provisioningSLA: 3 business days
    serviceUseCases:
      - JSON document workloads
      - MongoDB-compatible application backends
      - Content management data stores
    serviceOnboardingRequirements:
      - cost_center
      - project
      - environment
      - version
      - instance_types
      - Instance_count
