apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: amazon-elasticache
  title: Amazon ElastiCache
spec:
  type: service-offering
  lifecycle: production
  profile:
    cloudProvider: AWS
    serviceCategory: Database
    serviceDescription: Amazon ElastiCache offers fully managed Redis and Memcached. Seamlessly deploy, operate, and scale popular open source compatible in-memory data stores. Build data-intensive apps or improve the performance of your existing apps by retrieving data from high throughput and low latency in-memory data stores.
    serviceExternalDoc: https://docs.aws.amazon.com/ElastiCache/
    serviceInternalDoc: ./platforms/development/amazon/elasticache
    provisioningModel: Tier 2
    cloudAto:
      - CACE
    serviceOwner: Natasha Romanoff
    fedRampStatus: FedRAMP Certified
    trmStatus: Permitted
    trmLink: https://cloud-docs.cbp.dhs.gov/governance/trm.html#amazon-elasticache
    fundingApproach: ECSD pay
    approvalWorkflow: Manager Approval
    provisioningSLA: 3 business days
    serviceUseCases:
      - Application caching layers
      - Session store for web applications
      - Real-time leaderboard and counters
    serviceOnboardingRequirements:
      - cost-center
      - project
      - environment
      - mode
      - node-type
      - nodes
      - encryption-in-transit
      - encryption-at-rest
