apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: amazon-vpc
  title: Amazon VPC
spec:
  type: service-offering
  profile:
    cloudProvider: AWS
    serviceCategory: Infrastructure & Platforms
    serviceDescription: >-
      Amazon Virtual Private Cloud (Amazon VPC) is a logically isolated virtual network that closely
      resembles a traditional network and has subnets and IP addresses that are allocated to the
      various resources that are provisioned within the VPC. VPCs are configured by the
      administrators and are not a service that would be explicitly requested.
    serviceExternalDoc: https://aws.amazon.com/vpc/
    serviceInternalDoc: ./platforms/development/network
    provisioningModel: Tier 2
    cloudAto:
      - CACE
    serviceOwner: Natasha Romanoff
    fedRampStatus: FedRAMP Certified
    trmStatus: Permitted
    trmLink: https://cloud-docs.cbp.dhs.gov/governance/trm.html#amazon-vpc
    fundingApproach: ECSD pay
    approvalWorkflow: Manager Approval
    provisioningSLA: 2 business days
    serviceUseCases:
      - Isolated workload networking
      - Hybrid connectivity to on-prem
      - Multi-tier application segmentation
      - Security group enforcement
