apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: amazon-end-user-messaging
  title: Amazon End User Messaging
spec:
  type: service-offering
  lifecycle: production
  profile:
    cloudProvider: AWS
    serviceCategory: Messaging
    serviceDescription: AWS End User Messaging empowers developers to integrate scalable and reliable messaging capabilities into their applications. Whether it is time-sensitive alerts, one-time passwords, or two-way communications, AWS End User Messaging helps ensure your messages reach their local or global destination across channels like SMS, MMS. AWS End User Messaging helps unlock the full potential of your messaging strategy by connecting your applications directly to your end-users across the channels they use and trust.
    serviceExternalDoc: https://aws.amazon.com/sns/
    serviceInternalDoc: ./platforms/development/amazon/eum
    provisioningModel: Tier 3
    cloudAto:
      - CACE
    serviceOwner: Natasha Romanoff
    serviceLimitations: SMS/MMS campaign registration must be approved before send access is granted.
    fedRampStatus: FedRAMP In Process
    trmStatus: Restricted
    trmRestrictionOwner: CIM Integration Platform Team
    trmLink: https://cloud-docs.cbp.dhs.gov/governance/trm.html#amazon-end-user-messaging
    fundingApproach: Funding recouped
    approvalWorkflow: Security Review
    provisioningSLA: 10 business days
    serviceUseCases:
      - Time-sensitive SMS/MMS alerts
      - One-time passcode delivery
      - Two-way customer text messaging
    serviceOnboardingRequirements:
      - cost_center
      - project
      - environment
      - Estimated Monthly Message Volume - Optional (Less than 500 / Greater than 500 but less than 5000 / Greater than 5000)
      - Destination (Local or International)
      - Two-way SMS Messaging (Yes or No)
      - Originator Type (Long Code - Supports only voice messaging.; Short Code - Supports SMS and MMS messaging.; Toll-Free – Supports SMS, MMS, and voice messaging.; 10DLC - Supports SMS, MMS, and voice messaging.)
      - Registration Information (Please note it will take several weeks for registration to complete) (Enter Campaign Description (Identify who the sender is; Identify who the recipient is; Why messages are being sent to the intended recipient.); Company's SMS Terms & Conditions (URL or File, less than 500KB))
      - Company Privacy policy URL (Example - https://www.dhs.gov/topics/privacy)
      - Campaign opt-in workflow (Explain end-to-end how a user explicitly consents to receive text messages.)
      - Opt-in confirmation message (Provide the message sent to recipients confirming with them that they've opted in to your service.)
      - Help message (Provide the message sent to end-users when they send the 'HELP' keyword.)
      - Stop message (Provide the message sent to end-users when they send the opt-out keywords such as 'STOP'.)
      - Message Type - Transactional or Promotional (Needs to align with your campaign use case, if it's misaligned your registration will be denied.)
      - Use case – Details about how this campaign will be used for sending SMS messages.
      - Subscriber opt-in (Yes or No, Yes acknowledges you are required to collect and process consumer opt-ins.)
      - Subscriber opt-out (Yes or No, Yes acknowledges you are required to collect and process consumer opt-outs.)
      - Subscriber help (Yes or No, Yes confirms you've implemented automated 'HELP' replies with sender contact info.)
      - Message Sample (At least one sample is required, minimum 20 characters, limited to 1024 characters. Include a sample message for each message you plan on sending from this campaign, up to 5 samples.)
      - MMS Sample – Optional with File attachment
