apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: amazon-sagemaker-studio
  title: Amazon SageMaker Studio
spec:
  type: service-offering
  lifecycle: production
  profile:
    cloudProvider: AWS
    serviceCategory: AI & Machine Learning
    serviceDescription: Amazon SageMaker Studio provides a single, unified web-based interface with purpose-built tools to prepare, build, train, and deploy Machine Learning models using your preferred IDE.
    serviceExternalDoc: https://aws.amazon.com/sagemaker/studio/
    serviceInternalDoc: ./platforms/development/amazon/sagemaker-studio
    provisioningModel: Tier 3
    cloudAto:
      - CACE
    serviceOwner: Natasha Romanoff
    fedRampStatus: FedRAMP Certified
    trmStatus: Restricted
    trmRestrictionOwner: CIM AI Platform Team
    trmLink: https://cloud-docs.cbp.dhs.gov/governance/trm.html#amazon-sagemaker-studio
    fundingApproach: Funding recouped
    approvalWorkflow: Multi-Level Approval
    provisioningSLA: 10 business days
    serviceUseCases:
      - Unified ML development IDE
      - Notebook-based model experimentation
      - End-to-end ML workflow authoring
    serviceOnboardingRequirements:
      - cost_center
      - project (note that the project will be the SageMaker Studio domain name)
      - environment
