apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: amazon-groundtruth
  title: Amazon Groundtruth
spec:
  type: service-offering
  profile:
    cloudProvider: AWS
    serviceCategory: AI & Machine Learning
    serviceDescription: >-
      Amazon Ground Truth enables users with the ability to label image and text datasets to provide
      the correct metadata for Machine Learning (ML) model training. Auto-labeling is a ML enabled
      Ground Truth feature available to automatically complete labeling operations on a dataset
      while using only part of the dataset that has been already manually labeled within Ground
      Truth.
    serviceExternalDoc: https://aws.amazon.com/sagemaker/groundtruth/
    serviceInternalDoc: ./platforms/development/amazon/sagemaker-groundtruth
    provisioningModel: Tier 3
    cloudAto:
      - CACE
    serviceOwner: Natasha Romanoff
    fedRampStatus: FedRAMP Ready
    trmStatus: Restricted
    trmRestrictionOwner: CIM AI Platform Team
    trmLink: https://cloud-docs.cbp.dhs.gov/governance/trm.html#amazon-groundtruth
    fundingApproach: Funding recouped
    approvalWorkflow: Multi-Level Approval
    provisioningSLA: 10 business days
    serviceUseCases:
      - Training dataset labeling
      - Human-in-the-loop annotation
      - Auto-labeling for ML pipelines
