apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: amazon-rds-postgresql
  title: Amazon RDS PostgreSQL
spec:
  type: service-offering
  profile:
    cloudProvider: AWS
    serviceCategory: Database
    serviceDescription: >-
      Amazon RDS is a web service that makes it easier to set up, operate, and scale a relational
      database in the cloud. It provides cost-efficient, resizable capacity for an industry-standard
      relational database and manages common database administration tasks. RDS (Postgres)
      specifically makes it easy to set up, operate, and scale PostgreSQL deployments in the cloud.
    serviceExternalDoc: https://aws.amazon.com/rds/
    serviceInternalDoc: https://cloud-docs.cbp.dhs.gov/platforms/development/amazon/rds.html#postgresql
    provisioningModel: Tier 1
    cloudAto:
      - CACE
    serviceOwner: Natasha Romanoff
    fedRampStatus: FedRAMP Certified
    trmStatus: Permitted
    trmLink: https://cloud-docs.cbp.dhs.gov/governance/trm.html#amazon-rds-postgresql
    fundingApproach: ECSD pay
    approvalWorkflow: Auto-Approved
    provisioningSLA: 1 business day
    serviceUseCases:
      - PostgreSQL application backends
      - Geospatial data workloads
      - Multi-tenant SaaS databases
    serviceOnboardingRequirements:
      - cost_center
      - project
      - environment
      - Quantity
      - Engine (Postgres)
      - Instance Type/Instance Class
      - Multi-AZ
      - Storage
      - "RDS Proxy needed (without native connection pooling capabilities): Yes/No"
      - "Target database endpoint: If yes"
      - "Serverless (Aurora PostgreSQL/MySQL only): Yes/No"
