apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: amazon-eks
  title: Amazon EKS
spec:
  type: service-offering
  lifecycle: production
  profile:
    cloudProvider: AWS
    serviceCategory: Container Platform
    serviceDescription: Amazon EKS (Elastic Kubernetes Service) is a fully managed service that allows you to run Kubernetes on AWS without needing to install, operate, or maintain your own Kubernetes control plane. Because it is certified Kubernetes-conformant, any application running on standard upstream Kubernetes can easily migrate to Amazon EKS without any code changes.
    serviceExternalDoc: https://docs.aws.amazon.com/eks/
    serviceInternalDoc: ./platforms/cicd/eks/index
    provisioningModel: Tier 3
    cloudAto:
      - CACE
    serviceOwner: Natasha Romanoff
    fedRampStatus: FedRAMP Certified
    trmStatus: Restricted
    trmRestrictionOwner: CIM Container Platform Team
    trmLink: https://cloud-docs.cbp.dhs.gov/governance/trm.html#amazon-eks
    fundingApproach: Funding recouped
    approvalWorkflow: Architecture Review
    provisioningSLA: 10 business days
    serviceUseCases:
      - Containerized microservices
      - CI/CD workload hosting
      - Multi-tenant Kubernetes workloads
