apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: amazon-redshift
  title: Amazon Redshift
spec:
  type: service-offering
  profile:
    cloudProvider: AWS
    serviceCategory: Database
    serviceDescription: >-
      AWS Redshift is an Internet hosting service and data warehouse product which forms part of the
      larger cloud-computing platform Amazon Web Services. Now includes the Zero-ETL integration for
      easier data ingestion.
    serviceExternalDoc: https://docs.aws.amazon.com/redshift/
    serviceInternalDoc: ./platforms/development/amazon/redshift
    provisioningModel: Tier 2
    cloudAto:
      - CACE
    serviceOwner: Natasha Romanoff
    fedRampStatus: FedRAMP Certified
    trmStatus: Permitted
    trmLink: https://cloud-docs.cbp.dhs.gov/governance/trm.html#amazon-redshift
    fundingApproach: Funding recouped
    approvalWorkflow: Manager Approval
    provisioningSLA: 5 business days
    serviceUseCases:
      - Enterprise data warehousing
      - BI dashboard reporting
      - Zero-ETL analytics pipelines
    serviceOnboardingRequirements:
      - cost_center
      - project
      - environment
      - enable_logging (Optional)
      - "cluster_node_type (ex: \"ra3.xlplus\")"
      - cluster_number_of_nodes
      - zero-etl integration (Optional) (source RDS or cluster; target Redshift cluster)
