apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: amazon-rds
  title: Amazon RDS
spec:
  type: service-offering
  lifecycle: production
  profile:
    cloudProvider: AWS
    serviceCategory: Database
    serviceDescription: A managed relational database service that provides several familiar database engines to choose from, including PostgreSQL, MySQL, and Oracle.
    serviceExternalDoc: https://docs.aws.amazon.com/rds/
    serviceInternalDoc: ./platforms/development/amazon/rds
    provisioningModel: Tier 1
    cloudAto:
      - CACE
    serviceOwner: Natasha Romanoff
    fedRampStatus: FedRAMP Certified
    trmStatus: Permitted
    trmLink: https://cloud-docs.cbp.dhs.gov/governance/trm.html#amazon-rds
    fundingApproach: ECSD pay
    approvalWorkflow: Auto-Approved
    provisioningSLA: 1 business day
    serviceUseCases:
      - Transactional application databases
      - Reporting and analytics
      - COTS application backends
      - Disaster recovery replicas
    serviceOnboardingRequirements:
      - cost_center
      - project
      - environment
      - Quantity
      - Engine
      - Instance Type/Instance Class
      - Multi-AZ
      - Storage
      - 'RDS Proxy needed (without native connection pooling capabilities): Yes/No'
      - 'Target database endpoint: If yes'
      - 'Serverless (Aurora PostgreSQL/MySQL only): Yes/No'
