apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: amazon-rds-mysql
  title: Amazon RDS MySQL
spec:
  type: service-offering
  lifecycle: production
  profile:
    cloudProvider: AWS
    serviceCategory: Database
    serviceDescription: RDS is a distributed relational database service by Amazon Web Services (AWS). It is a web service running "in the cloud" designed to simplify the setup, operation, and scaling of a relational database for use in applications. Complex administration processes like patching the database software, backing up databases and enabling point-in-time recovery are managed automatically. Scaling storage and compute resources can be performed by a single API call.
    serviceExternalDoc: https://aws.amazon.com/rds/
    serviceInternalDoc: https://cloud-docs.cbp.dhs.gov/platforms/development/amazon/rds.html#mysql
    provisioningModel: Tier 1
    cloudAto:
      - CACE
    serviceOwner: Natasha Romanoff
    fedRampStatus: FedRAMP Certified
    trmStatus: Permitted
    trmLink: https://cloud-docs.cbp.dhs.gov/governance/trm.html#amazon-rds-mysql
    fundingApproach: ECSD pay
    approvalWorkflow: Auto-Approved
    provisioningSLA: 1 business day
    serviceUseCases:
      - MySQL application backends
      - Legacy database lift-and-shift
      - Web application data stores
    serviceOnboardingRequirements:
      - cost_center
      - project
      - environment
      - Quantity
      - Engine (MySQL)
      - Instance Type/Instance Class
      - Multi-AZ
      - Storage
      - 'RDS Proxy needed (without native connection pooling capabilities): Yes/No'
      - 'Target database endpoint: If yes'
      - 'Serverless (Aurora PostgreSQL/MySQL only): Yes/No'
