apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: amazon-rds-aurora
  title: Amazon RDS Aurora
spec:
  type: service-offering
  lifecycle: production
  profile:
    cloudProvider: AWS
    serviceCategory: Database
    serviceDescription: Amazon Aurora is a MySQL and PostgreSQL-compatible relational database built for the cloud that combines the performance and availability of traditional enterprise databases with the simplicity and cost-effectiveness of open source databases. Amazon Aurora is up to five times faster than standard MySQL databases and three times faster than standard PostgreSQL databases. It provides the security, availability, and reliability of commercial databases at 1/10th the cost. Amazon Aurora is fully managed by Amazon Relational Database Service (RDS), which automates time-consuming administration tasks like hardware provisioning, database setup, patching, and backups. Amazon Aurora features a distributed, fault-tolerant, self-healing storage system that auto-scales up to 128TB per database instance. It delivers high performance and availability with up to 15 low-latency read replicas, point-in-time recovery, continuous backup to Amazon S3, and replication across three Availability Zones.
    serviceExternalDoc: https://aws.amazon.com/rds/aurora/
    serviceInternalDoc: ./platforms/development/amazon/rds
    provisioningModel: Tier 1
    cloudAto:
      - CACE
    serviceOwner: Natasha Romanoff
    fedRampStatus: FedRAMP Certified
    trmStatus: Permitted
    trmLink: https://cloud-docs.cbp.dhs.gov/governance/trm.html#amazon-rds-aurora
    fundingApproach: ECSD pay
    approvalWorkflow: Auto-Approved
    provisioningSLA: 1 business day
    serviceUseCases:
      - High-throughput relational workloads
      - MySQL/PostgreSQL-compatible migrations
      - Read-replica scaling for reporting
