apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: amazon-mq
  title: Amazon MQ
spec:
  type: service-offering
  profile:
    cloudProvider: AWS
    serviceCategory: Messaging
    serviceDescription: >-
      Amazon MQ is a managed message broker service for Apache ActiveMQ and RabbitMQ that makes it
      easy to set up and operate message brokers on AWS. Amazon MQ reduces your operational
      responsibilities by managing the provisioning, setup, and maintenance of message brokers for
      you. Because Amazon MQ connects to your current applications with industry-standard APIs and
      protocols, you can easily migrate to AWS without having to rewrite code.
    serviceExternalDoc: https://docs.aws.amazon.com/amazon-mq/
    serviceInternalDoc: ./platforms/development/amazon/mq
    provisioningModel: Tier 2
    cloudAto:
      - CACE
    serviceOwner: Natasha Romanoff
    fedRampStatus: FedRAMP Certified
    trmStatus: Permitted
    trmLink: https://cloud-docs.cbp.dhs.gov/governance/trm.html#amazon-mq
    fundingApproach: Funding recouped
    approvalWorkflow: Manager Approval
    provisioningSLA: 3 business days
    serviceUseCases:
      - Legacy ActiveMQ/RabbitMQ migrations
      - Protocol-standard message brokering
      - Enterprise application integration
    serviceOnboardingRequirements:
      - cost_center
      - project
      - environment
      - Quantity
      - Engine Type (ActiveMQ or RabbitMQ)
      - Deployment mode (SINGLE_INSTANCE [default], ACTIVE_STANDBY_MULTI_AZ, or CLUSTER_MULTI_AZ)
      - Broker instance types (see AWS documentation for supported instance types)
