apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: aws-iam
  title: AWS IAM
spec:
  type: service-offering
  profile:
    cloudProvider: AWS
    serviceCategory: Identity & Access Management
    serviceDescription: >-
      AWS IAM (Identity and Access Management) is a core security service that controls who can
      authenticate (who you are) and authorize (what you are allowed to do) within your AWS
      environment. Access is denied by default unless explicitly granted by a policy.
    serviceExternalDoc: https://docs.aws.amazon.com/iam/
    serviceInternalDoc: https://cloud-docs.cbp.dhs.gov/platforms/development/amazon/iam.html
    provisioningModel: Tier 1
    cloudAto:
      - CACE
    serviceOwner: Natasha Romanoff
    fedRampStatus: FedRAMP Certified
    trmStatus: Permitted
    trmLink: https://cloud-docs.cbp.dhs.gov/governance/trm.html#aws-iam
    fundingApproach: ECSD pay
    approvalWorkflow: Auto-Approved
    provisioningSLA: Same day
    serviceUseCases:
      - Role-based access control
      - Cross-account resource sharing
      - Service-to-service authentication
      - Least-privilege policy enforcement
