apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: aws-secrets-manager
  title: AWS Secrets Manager
spec:
  type: service-offering
  profile:
    cloudProvider: AWS
    serviceCategory: Secret Management
    serviceDescription: >-
      AWS Secrets Manager helps you manage, retrieve, and rotate credentials, tokens, API keys, and
      other secrets throughout their lifecycles. Many AWS services store and use secrets in Secrets
      Manager.
    serviceExternalDoc: https://aws.amazon.com/secrets-manager/
    serviceInternalDoc: ./platforms/development/amazon/secrets-mngr
    provisioningModel: Tier 1
    cloudAto:
      - CACE
    serviceOwner: Natasha Romanoff
    fedRampStatus: FedRAMP Certified
    trmStatus: Permitted
    trmLink: https://cloud-docs.cbp.dhs.gov/governance/trm.html#aws-secrets-manager
    fundingApproach: ECSD pay
    approvalWorkflow: Auto-Approved
    provisioningSLA: Same day
    serviceUseCases:
      - Database credential rotation
      - API key storage
      - Application config secrets
      - Cross-service secret sharing
