apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: aws-transfer-family
  title: AWS Transfer Family
spec:
  type: service-offering
  profile:
    cloudProvider: AWS
    serviceCategory: Migration & Transfer
    serviceDescription: AWS Transfer is a fully managed service for transfer of files over SFTP.
    serviceExternalDoc: https://aws.amazon.com/aws-transfer-family
    serviceInternalDoc: ./platforms/development/amazon/transfer
    provisioningModel: Tier 2
    cloudAto:
      - CACE
    serviceOwner: Natasha Romanoff
    fedRampStatus: FedRAMP Certified
    trmStatus: Permitted
    trmLink: https://cloud-docs.cbp.dhs.gov/governance/trm.html#aws-transfer-family
    fundingApproach: Funding recouped
    approvalWorkflow: Manager Approval
    provisioningSLA: 5 business days
    serviceUseCases:
      - SFTP file exchange with external partners
      - Legacy file-transfer workflow migration
      - Managed inbound/outbound file transfer
    serviceOnboardingRequirements:
      - cost_center
      - project
      - environment
