apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: aws-backup
  title: AWS Backup
spec:
  type: service-offering
  lifecycle: production
  profile:
    cloudProvider: AWS
    serviceCategory: Storage
    serviceDescription: AWS Backup is a fully managed service that centralizes and automates data protection across AWS services and hybrid workloads.
    serviceExternalDoc: https://docs.aws.amazon.com/aws-backup/
    serviceInternalDoc: https://cloud-docs.cbp.dhs.gov/
    provisioningModel: Tier 1
    cloudAto:
      - CACE
    serviceOwner: Natasha Romanoff
    fedRampStatus: FedRAMP Certified
    trmStatus: Permitted
    trmLink: https://cloud-docs.cbp.dhs.gov/governance/trm.html#aws-backup
    fundingApproach: ECSD pay
    approvalWorkflow: Auto-Approved
    provisioningSLA: Same day
    serviceUseCases:
      - Centralized backup policy management
      - Cross-service data protection
      - Automated backup retention and lifecycle
