apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: aws-security-hub
  title: AWS Security Hub
spec:
  type: service-offering
  profile:
    cloudProvider: AWS
    serviceCategory: Security Scanning
    serviceDescription: >-
      AWS Security Hub is a cloud security posture management (CSPM) and SOAR (Security
      Orchestration, Automation, and Response) service. It evaluates your AWS environment against
      industry standards and best practices and compliance frameworks like CIS, PCI DSS, and NIST,
      assigning you a percentage-based security score.
    serviceExternalDoc: https://aws.amazon.com/security-hub/
    serviceInternalDoc: >-
      https://cloud-docs.cbp.dhs.gov/governance/compliancefaq.html#threat-monitoring-and-compliance-standards
    provisioningModel: Tier 1
    cloudAto:
      - CACE
    serviceOwner: Natasha Romanoff
    fedRampStatus: FedRAMP Certified
    trmStatus: Permitted
    trmLink: https://cloud-docs.cbp.dhs.gov/governance/trm.html#aws-security-hub
    fundingApproach: ECSD pay
    approvalWorkflow: Auto-Approved
    provisioningSLA: Same day
    serviceUseCases:
      - Cloud security posture management
      - Compliance scoring against CIS/PCI DSS/NIST
      - Centralized security finding aggregation
