apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: demilitarized-zone
  title: Demilitarized Zone
spec:
  type: service-offering
  profile:
    cloudProvider: AWS
    serviceCategory: Infrastructure & Platforms
    serviceDescription: >-
      CBP AWS Trusted Internet Connections 3.0 (in short CATIC 3.0) allows CBP project teams to
      provide external connectivity to their services running in the on-premises and cloud. CATIC
      3.0 is CBP's alternative to existing demilitarized zones (DMZ) — DHS TIC and DHS Cloudflare —
      to expose CBP services to users in the public Internet.
    serviceExternalDoc: https://docs.aws.amazon.com/
    serviceInternalDoc: https://gitlab-pages.cbp.dhs.gov/cloud/documentation/cim-7266/platforms/dmz/
    provisioningModel: Tier 3
    cloudAto:
      - CACE
    serviceOwner: Natasha Romanoff
    fedRampStatus: FedRAMP Certified
    trmStatus: Restricted
    trmRestrictionOwner: CIM Network Services
    trmLink: https://cloud-docs.cbp.dhs.gov/governance/trm.html#demilitarized-zone
    fundingApproach: Funding recouped
    approvalWorkflow: Security Review
    provisioningSLA: 10 business days
    serviceUseCases:
      - External connectivity for internet-facing services
      - Trusted Internet Connection (TIC) compliance
      - Public-facing API exposure
