apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: filestore
  title: Filestore
spec:
  type: service-offering
  profile:
    cloudProvider: Google Cloud
    serviceCategory: Storage
    serviceDescription: >-
      High-performance, fully managed NFS file storage for applications requiring a file system
      interface.
    serviceExternalDoc: https://cloud.google.com/docs
    serviceInternalDoc: https://cloud-docs.cbp.dhs.gov/
    provisioningModel: Tier 1
    cloudAto:
      - MAGE
    serviceOwner: Carol Danvers
    fedRampStatus: FedRAMP Certified
    trmStatus: Permitted
    trmLink: https://cloud-docs.cbp.dhs.gov/governance/trm.html#filestore
    fundingApproach: ECSD pay
    approvalWorkflow: Auto-Approved
    provisioningSLA: 1 business day
    serviceUseCases:
      - Kubernetes persistent volumes
      - Content management systems
      - Data analytics file shares
      - Legacy NFS workloads
