apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: firestore
  title: Cloud Firestore
spec:
  type: service-offering
  profile:
    cloudProvider: Google Cloud
    serviceCategory: Database
    serviceDescription: Serverless, scalable NoSQL document database built for automatic scaling and high performance.
    serviceExternalDoc: https://cloud.google.com/docs
    serviceInternalDoc: https://cloud-docs.cbp.dhs.gov/
    provisioningModel: Tier 1
    cloudAto:
      - MAGE
    serviceOwner: Carol Danvers
    fedRampStatus: FedRAMP Certified
    trmStatus: Permitted
    trmLink: https://cloud-docs.cbp.dhs.gov/governance/trm.html#firestore
    fundingApproach: ECSD pay
    approvalWorkflow: Auto-Approved
    provisioningSLA: Same day
    serviceUseCases:
      - Mobile and web app data sync
      - Real-time collaboration features
      - Offline-capable applications
      - Document-oriented data models
