apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: gke
  title: Google Kubernetes Engine
spec:
  type: service-offering
  lifecycle: production
  profile:
    cloudProvider: Google Cloud
    serviceCategory: Compute
    serviceDescription: Managed Kubernetes service to deploy, manage, and scale containerized applications on GCP.
    serviceExternalDoc: https://cloud.google.com/docs
    serviceInternalDoc: https://cloud-docs.cbp.dhs.gov/
    provisioningModel: Tier 3
    cloudAto:
      - MAGE
    serviceOwner: Carol Danvers
    serviceLimitations: Autopilot mode not yet supported.
    fedRampStatus: FedRAMP Certified
    trmStatus: Restricted
    trmRestrictionOwner: CIM Compute Platform
    trmLink: https://cloud-docs.cbp.dhs.gov/governance/trm.html#gke
    fundingApproach: Funding recouped
    approvalWorkflow: Architecture Review
    provisioningSLA: 10 business days
    serviceUseCases:
      - Container orchestration
      - Microservices deployment
      - CI/CD workload hosting
      - Multi-cluster federation
