apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: secret-manager
  title: Secret Manager
spec:
  type: service-offering
  lifecycle: production
  profile:
    cloudProvider: Google Cloud
    serviceCategory: Security
    serviceDescription: Store API keys, passwords, certificates, and other sensitive data as versioned secret resources.
    serviceExternalDoc: https://cloud.google.com/docs
    serviceInternalDoc: https://cloud-docs.cbp.dhs.gov/
    provisioningModel: Tier 1
    cloudAto:
      - MAGE
    serviceOwner: Carol Danvers
    fedRampStatus: FedRAMP Certified
    trmStatus: Permitted
    trmLink: https://cloud-docs.cbp.dhs.gov/governance/trm.html#secret-manager
    fundingApproach: ECSD pay
    approvalWorkflow: Auto-Approved
    provisioningSLA: Same day
    serviceUseCases:
      - Sensitive config value storage
      - Secret versioning and rotation
      - Audit trail for secret access
      - CI/CD pipeline credentials
